ALTER TABLE public.trip ADD COLUMN IF NOT EXISTS destination_geocode_failed_at timestamptz;

ALTER TABLE public.notification_preferences
  ADD COLUMN IF NOT EXISTS push_reminders boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS email_reminders boolean NOT NULL DEFAULT true;

CREATE TABLE public.push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL UNIQUE CHECK (endpoint LIKE 'https://%' AND length(endpoint) <= 1024),
  p256dh text NOT NULL CHECK (length(p256dh) BETWEEN 40 AND 200),
  auth text NOT NULL CHECK (length(auth) BETWEEN 8 AND 64),
  user_agent text CHECK (user_agent IS NULL OR length(user_agent) <= 300),
  created_at timestamptz NOT NULL DEFAULT now(),
  last_success_at timestamptz,
  failed_count integer NOT NULL DEFAULT 0
);
CREATE INDEX push_subscriptions_user_idx ON public.push_subscriptions(user_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions TO authenticated;
GRANT ALL ON public.push_subscriptions TO service_role;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own push subscriptions read" ON public.push_subscriptions FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Own push subscriptions insert" ON public.push_subscriptions FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "Own push subscriptions update" ON public.push_subscriptions FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Own push subscriptions delete" ON public.push_subscriptions FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE TABLE public.reminder_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL REFERENCES public.trip(id) ON DELETE CASCADE,
  reminder_key text NOT NULL,
  channel text NOT NULL CHECK (channel IN ('push','email')),
  sent_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, reminder_key, channel)
);
CREATE INDEX reminder_deliveries_user_sent_idx ON public.reminder_deliveries(user_id, sent_at);
GRANT SELECT ON public.reminder_deliveries TO authenticated;
GRANT ALL ON public.reminder_deliveries TO service_role;
ALTER TABLE public.reminder_deliveries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Own reminder deliveries read" ON public.reminder_deliveries FOR SELECT TO authenticated USING (user_id = auth.uid());

-- Server-only material: push keys generated by the reminders function, and the cron caller secret.
CREATE TABLE public.push_server_keys (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  public_key text NOT NULL,
  private_jwk jsonb NOT NULL,
  public_jwk jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.push_server_keys TO service_role;
ALTER TABLE public.push_server_keys ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.server_job_secrets (
  name text PRIMARY KEY,
  secret text NOT NULL CHECK (length(secret) >= 32),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.server_job_secrets TO service_role;
ALTER TABLE public.server_job_secrets ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.get_push_public_key()
RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT public_key FROM public.push_server_keys WHERE id = 1
$$;
REVOKE ALL ON FUNCTION public.get_push_public_key() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_push_public_key() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.ops_set_setting(p_key text, p_value text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE v_actor uuid := auth.uid(); v_old text;
BEGIN
  IF v_actor IS NULL OR NOT public.has_role(v_actor,'admin'::public.app_role) THEN RAISE EXCEPTION 'platform_admin_required' USING ERRCODE='42501'; END IF;
  IF p_key NOT IN ('signups_open','hansie_enabled','payments_enabled','maintenance_mode','sandbox_pro_enabled','reminders_enabled') THEN RAISE EXCEPTION 'unknown_setting' USING ERRCODE='23514'; END IF;
  IF p_value NOT IN ('true','false') THEN RAISE EXCEPTION 'invalid_setting_value' USING ERRCODE='23514'; END IF;
  SELECT value INTO v_old FROM public.app_settings WHERE key = p_key;
  INSERT INTO public.app_settings(key, value) VALUES (p_key, p_value)
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.admin_audit_log(actor_user_id, action, target_type, target_id, metadata)
  VALUES (v_actor, 'setting.changed', 'app_setting', p_key, jsonb_build_object('from', v_old, 'to', p_value));
  RETURN true;
END $function$;

CREATE OR REPLACE FUNCTION public.ops_delete_user(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE v_actor uuid := auth.uid(); v_email text;
BEGIN
  IF v_actor IS NULL OR NOT public.has_role(v_actor,'admin'::public.app_role) THEN RAISE EXCEPTION 'platform_admin_required' USING ERRCODE='42501'; END IF;
  IF p_user_id = v_actor THEN RAISE EXCEPTION 'cannot_delete_self' USING ERRCODE='23514'; END IF;
  SELECT email INTO v_email FROM auth.users WHERE id = p_user_id;
  IF v_email IS NULL THEN RAISE EXCEPTION 'user_not_found' USING ERRCODE='P0002'; END IF;
  IF EXISTS (SELECT 1 FROM public.user_roles r WHERE r.user_id = p_user_id AND r.role = 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'cannot_delete_platform_admin' USING ERRCODE='42501';
  END IF;

  DELETE FROM public.push_subscriptions WHERE user_id = p_user_id;
  DELETE FROM public.reminder_deliveries WHERE user_id = p_user_id;
  DELETE FROM public.calendar_feeds WHERE user_id = p_user_id;
  DELETE FROM public.trip_traveler_profiles WHERE user_id = p_user_id;
  DELETE FROM public.trip_members WHERE user_id = p_user_id;
  DELETE FROM public.notifications WHERE user_id = p_user_id;
  DELETE FROM public.notification_preferences WHERE user_id = p_user_id;
  DELETE FROM public.decision_votes WHERE user_id = p_user_id;
  DELETE FROM public.expense_splits WHERE user_id = p_user_id;
  DELETE FROM public.entitlements WHERE user_id = p_user_id;
  DELETE FROM public.ai_usage_events WHERE user_id = p_user_id;
  DELETE FROM public.activity_log WHERE user_id = p_user_id;
  DELETE FROM public.client_error_events WHERE user_id = p_user_id;
  DELETE FROM public.trip_invite_uses WHERE user_id = p_user_id;
  DELETE FROM public.user_roles WHERE user_id = p_user_id;
  DELETE FROM public.payment_details WHERE user_id = p_user_id;
  DELETE FROM public.profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;

  INSERT INTO public.admin_audit_log(actor_user_id, action, target_type, target_id, metadata)
  VALUES (v_actor, 'user.deleted', 'user', p_user_id::text, jsonb_build_object('email', v_email));
  RETURN true;
END $function$;